#include "cli/Usage.h"
#include <iostream>

void printUsage(const char* argv0) {
    std::cout
        << "Usage: " << argv0 << " [options]\n"
        << "\nBasic\n"
        << "  --headless            Run without window\n"
        << "  --map <path>          Map JSON for watch/single-map train (default: maps/map1_chicanes_infernais.json)\n"
        << "  --population <N>      Number of cars (default: 1)\n"
        << "  --seed <S>            RNG seed (default: 42)\n"
        << "  --threads <K>         Thread count (default: hardware_concurrency)\n"
        << "  --benchmark           Run benchmark and exit\n"
        << "\nTraining\n"
        << "  --train               Run generational training loop\n"
        << "  --algo <name>         Training algorithm: genetic|random_search|hillclimb (default: genetic)\n"
        << "  --generations <N>     Number of generations (default: 100)\n"
        << "  --out <dir>           Output directory for weights (default: out/)\n"
        << "  --load <file.rnnw>    With --train: seed population from champion. Without: watch the network\n"
        << "  --watch <file.rnnw>   Watch a saved network drive (no training)\n"
        << "  --versus <file.rnnw>  Human (↑↓←→ / WASD) vs saved network. Yellow = you, green = AI\n"
        << "                        Use --population N to race against N AIs (default: 1)\n"
        << "  --versus-noise <s>    Gaussian weight noise per AI copy so they diverge (default: 0.02)\n"
        << "\nMulti-map training & robustness\n"
        << "  --train-maps <a,b,..> Comma-separated list of training maps\n"
        << "  --val-maps <x,y>      Comma-separated validation maps (model selection when --select-by-val)\n"
        << "  --test-maps <x,y>     Comma-separated test maps: report-only, never used in selection\n"
        << "  --select-by-val       Save best.rnnw by validation progress (top-K) instead of train fitness\n"
        << "  --val-select-topk <T> Train genomes evaluated on val for selection (default 1)\n"
        << "  --random-spawn        Start each training episode at a random point on the track\n"
        << "  --sensor-noise <s>    Gaussian noise (stddev) added to ray readings in training\n"
        << "  --episodes-per-eval <N> Episodes per (genome,map), aggregated (default 1)\n"
        << "  --episode-agg <mode>  Combine episodes: mean (default) | min\n"
        << "  --augment <list>      Add transformed train maps: mirror,reverse,width:0.85,width:1.15\n"
        << "  --procedural-train <K> Generate K random tracks (seeded) into the train set\n"
        << "  --procedural-val <K>  Generate K random tracks (seeded) into the validation set\n"
        << "  --proc-width-min <w>  Min sampled width for procedural tracks (default 55)\n"
        << "  --proc-width-max <w>  Max sampled width for procedural tracks (default 110)\n"
        << "  --dump-gen-maps <dir> Save augmented+procedural train maps as JSON to <dir> before training\n"
        << "  --fitness-agg <mode>  Aggregation: cvar-rank (default) | min | mean | cvar-raw\n"
        << "  --cvar-alpha <α>      CVaR tail fraction in (0,1] (default: 0.5). Used with cvar-rank/cvar-raw\n"
        << "  --map-norm <mode>     Per-map normalisation: zscore (default) | minmax | progress\n"
        << "                        Ignored under cvar-rank (ranks are scale-invariant)\n"
        << "  --curriculum <mode>   Map curriculum: linear (default) | none | explicit\n"
        << "  --curriculum-start <k>  Initial active map count for linear (default: 2)\n"
        << "  --curriculum-step <g>   Gens between additions for linear (default: 15)\n"
        << "  --curriculum-schedule <g1,g2,...>  Gen thresholds for explicit (M-1 values)\n"
        << "  --hidden <N>          Hidden layer size override (default: 32)\n"
        << "  --log-csv             Write training_log.csv and held_out_log.csv to --out dir\n"
        << "\nPerformance & map prioritization\n"
        << "  --episode-timeout SEC  Max episode length in seconds (default: 30)\n"
        << "  --curriculum-pin IDX  Comma-separated map indices always active (e.g. \"5\" or \"3,5\")\n"
        << "  --map-weights W1,...   Per-map weights for cvar-rank aggregation (e.g. \"1,1,1,1,1,3\")\n"
        << "                         Length must match --train-maps count; each weight > 0\n"
        << "  --progressive-frac F  Fraction of pop evaluated on maps[1..] after map[0] (default: 1.0)\n"
        << "  --finetune-map NAME   Fine-tune champion on a single map (requires --load)\n"
        << "                         Accepts bare name (map6_chicanes_infernais) or full path\n"
        << "\n  Default when --train is active and no --train-maps is given:\n"
        << "    all *.json in maps/, sorted; first 6 = train, last 2 = val (reproducible split).\n"
        << "  Single-map compat: --map without --train-maps trains only on that map.\n"
        << "\n  Baseline (old behaviour) reproducible with:\n"
        << "    --fitness-agg min --map-norm progress --curriculum none\n"
        << "\nConfig file\n"
        << "  --config <file.json>  Load defaults from JSON file (CLI flags override)\n"
        << "  Auto-detected: train.json in the current directory if it exists\n"
        << "  Keys match flag names with underscores: population, train_maps, cvar_alpha...\n"
        << "  Arrays accepted for train_maps, val_maps, test_maps, augment, map_weights\n";
}
